# Generated by Django 2.0 on 2017-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drivers', models.IntegerField(default=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stops', models.ManyToManyField(to='vrp.Address')),
            ],
        ),
    ]
