# Generated by Django 2.0 on 2017-12-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0004_auto_20171214_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=18, default=48.721287, max_digits=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=18, default=18.5491726, max_digits=20),
        ),
    ]
