# Generated by Django 2.0 on 2017-12-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0005_auto_20171214_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=7)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='end_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_address', to='vrp.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_location',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='start_address', to='vrp.Address'),
            preserve_default=False,
        ),
    ]
