# Generated by Django 2.0 on 2017-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0006_auto_20171216_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='comment',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.IntegerField(default=8, help_text='Average fuel consumption per 100 km'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=7, help_text='number of passenger seats'),
        ),
    ]
