# Generated by Django 2.0 on 2017-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0007_auto_20171216_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='vehicles',
            field=models.ManyToManyField(to='vrp.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Average fuel consumption per 100 km', max_digits=4),
        ),
    ]
