# Generated by Django 2.0 on 2017-12-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0010_route_point_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stop',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
